In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
# Sentance
sent =[
    'the glass of milk',
    'the glass of juice',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
# Define the vocabulary size

voc_size = 10000

In [ ]:
# One Hot Representation
one_hot_repe=[one_hot(words,voc_size) for words in sent]
one_hot_repe

[[491, 1054, 7645, 4264],
 [491, 1054, 7645, 551],
 [2788, 7116, 527, 8963, 591],
 [2788, 7116, 527, 8963, 2913],
 [8911, 491, 7848, 7645, 3987],
 [7833, 1890, 6747, 8963]]

In [ ]:
# Word embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [ ]:
sent_lengh = 8
Embedded_docs=pad_sequences(one_hot_repe,padding='pre',maxlen=sent_lengh)
print(Embedded_docs)

[[   0    0    0    0  491 1054 7645 4264]
 [   0    0    0    0  491 1054 7645  551]
 [   0    0    0 2788 7116  527 8963  591]
 [   0    0    0 2788 7116  527 8963 2913]
 [   0    0    0 8911  491 7848 7645 3987]
 [   0    0    0    0 7833 1890 6747 8963]]


In [ ]:
# Feature representation
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_lengh))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(Embedded_docs)

1/1 [==============================] - 0s 173ms/step


array([[[ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
          3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
          9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
          3.66100930e-02],
        [ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
          3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
          9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
          3.66100930e-02],
        [ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
          3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
          9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
          3.66100930e-02],
        [ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
          3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
          9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
          3.66100930e-02],
        [ 1.31655484e-04,  2.40051858e-02, -1.71157606e-02,
          4.34628390e-02, -2.81537659e-02, -1.17805824e-02,
          7.89608806e-03,  1.13505945e-02, -3.567296

In [ ]:
Embedded_docs[0]

array([   0,    0,    0,    0,  491, 1054, 7645, 4264])

In [ ]:
model.predict(Embedded_docs[0])

1/1 [==============================] - 0s 30ms/step


array([[ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
         3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
         9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
         3.66100930e-02],
       [ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
         3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
         9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
         3.66100930e-02],
       [ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
         3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
         9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
         3.66100930e-02],
       [ 3.76131795e-02, -2.01984998e-02,  1.00568421e-02,
         3.69454361e-02,  1.19192228e-02,  3.83460410e-02,
         9.28863883e-05, -1.32069364e-02,  1.05981715e-02,
         3.66100930e-02],
       [ 1.31655484e-04,  2.40051858e-02, -1.71157606e-02,
         4.34628390e-02, -2.81537659e-02, -1.17805824e-02,
         7.89608806e-03,  1.13505945e-02, -3.56729627e-02,
         2.